controller_names:
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller


scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - ur_shoulder_pan_joint
    - ur_shoulder_lift_joint
    - ur_elbow_joint
    - ur_wrist_1_joint
    - ur_wrist_2_joint
    - ur_wrist_3_joint


joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - ur_shoulder_pan_joint
    - ur_shoulder_lift_joint
    - ur_elbow_joint
    - ur_wrist_1_joint
    - ur_wrist_2_joint
    - ur_wrist_3_joint
